int alphaToNum(char a);
char numToAlpha(int a);
long convertToNum(char* num);
long toDec(char* num, int b);
long toBin(char* num, int b);
void reverse(char* num);
int getLen(long num);
char* toHex(char* num, int b);
long toOct(char* num, int b);
void prettyPrint_ops(char* num1, char* type1, char* num2, char* type2);
void prettyPrint_opi(char* num1, char* type1, int num2, char* type2);

void read(int f[][10], int r0, int c0);
void display(int f[][10], int r2, int c2);
void add(int f[][10], int s[][10], int r[][10], int x, int y);
void subtract(int f[][10], int s[][10], int r[][10], int x, int y);
void scalarm(int f[][10], int r[][10], int scalar, int x, int y);
void multi(int f[][10], int s[][10], int r[][10], int r1, int c2, int r2);
void transpose(int f[][10], int x, int y);
float det(int f[][10], int n);
void cofac(int f[][10], int t[][10], int z, int i, int n);
int dsum(int f[][10], int n);
int adsum(int f[][10], int n);
void rsum(int f[][10], int n, int m);
void csum(int f[][10], int n, int m);
void adjoint(int f[][10], int r[][10], int n, int m);
void matMain();

void A_Circle(char c1);
void A_Rect(char r1);
void A_Sq(char sq1);
void A_Rhom(char rh1);
void A_Prll(char prl1);
void A_Tri(char tri1);
void A_trpzoid(char trp1);
void A_SemiCrcl(char sc1);
void V_Cboid(char cuboid);
void V_Cube(char cube);
void V_Cyln(char cyl1);
void V_Cone(char cone1);
void V_Sphere(char sph1);
void V_HSphere(char HS1);
void V_Frustrum(char Frstm1);
void quit();
void areaVolMain();